version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "15433:1433"
    environment:
      SA_PASSWORD: ${AzureWebJobsSQLPassword}
      MSSQL_SA_PASSWORD: ${AzureWebJobsSQLPassword}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql_data: