name: mssql-database
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "placeholderForContainer1475"
      SA_PASSWORD: "placeholderForContainer1475"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - sqlnetwork

networks:
  sqlnetwork:
    driver: bridge