parameters:
    - name: nodeVersion
      type: string
    - name: testCommand
      type: string
      default: test

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: ${{ parameters.nodeVersion }}
      displayName: 'Install Node ${{ parameters.nodeVersion }}'
      retryCountOnTaskFailure: 10
    - bash: |
        docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker ps
      displayName: "Start CosmosDB Emulator"
    - bash: |
        docker compose -f src/utils/eventhub/docker-compose.yml pull
        docker compose -f src/utils/eventhub/docker-compose.yml up -d
      displayName: 'Install Azurite and Start EventHub Emulator'
    - bash: |
        npm run ${{ parameters.testCommand }}
      displayName: 'Run tests Node ${{ parameters.nodeVersion }}'
      continueOnError: true