parameters:
    - name: nodeVersion
      type: string

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: ${{ parameters.nodeVersion }}
      displayName: 'Install Node ${{ parameters.nodeVersion }}'
      retryCountOnTaskFailure: 10
    - bash: |
        docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker ps
      displayName: "Start CosmosDB Emulator"
    - bash: |
        npm run testOldConfig
      displayName: 'Run tests Node ${{ parameters.nodeVersion }}'
      continueOnError: true