parameters:
    - name: nodeVersion
      type: string
    - name: testCommand
      type: string
      default: test

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: ${{ parameters.nodeVersion }}
      displayName: 'Install Node ${{ parameters.nodeVersion }}'
      retryCountOnTaskFailure: 10
    - bash: |
        docker compose -f src/utils/eventhub/docker-compose.yml pull
        docker compose -f src/utils/eventhub/docker-compose.yml up -d
      displayName: 'Install Azurite and Start EventHub Emulator'
    - bash: |
        echo "Waiting 20s for EventHub Emulator to boot..."
        sleep 20
        echo "=== EventHub Emulator Logs ==="
        docker logs eventhubs-emulator || echo "Failed to get emulator logs"
      displayName: 'Output EventHub Emulator Logs'
    - bash: |
        npm run ${{ parameters.testCommand }}
      displayName: 'Run tests Node ${{ parameters.nodeVersion }}'
      continueOnError: true