jobs:
    - job:
      steps:
          - template: /azure-pipelines/templates/build.yml@self

          - task: AzureCLI@2
            displayName: 'Create resources'
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm run createResources'

          - pwsh: |
                .\scripts\install-func-cli.ps1
            displayName: 'Install func cli'

          - template: /azure-pipelines/templates/build-apps.yml@self

          # Run tests Node 18
          - task: NodeTool@0
            inputs:
                versionSpec: 18.x
            displayName: 'Install Node 18'
            retryCountOnTaskFailure: 10
          - task: AzureCLI@2
            displayName: 'Run tests Node 18'
            continueOnError: true
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm test'

          # Run tests for old config (just one Node.js version is enough)
          - task: AzureCLI@2
            displayName: 'Run tests old config'
            continueOnError: true
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm run testOldConfig'

          # Run tests Node 20
          - task: NodeTool@0
            inputs:
                versionSpec: 20.x
            displayName: 'Install Node 20'
            retryCountOnTaskFailure: 10
          - task: AzureCLI@2
            displayName: 'Run tests Node 20'
            continueOnError: true
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm test'

          # Run tests Node 22
          - task: NodeTool@0
            inputs:
                versionSpec: 22.x
            displayName: 'Install Node 22'
            retryCountOnTaskFailure: 10
          - task: AzureCLI@2
            displayName: 'Run tests Node 22'
            continueOnError: true
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm test'

          - task: AzureCLI@2
            displayName: 'Delete resources'
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm run deleteResources'
            condition: succeededOrFailed()

          - task: PublishTestResults@2
            displayName: 'Publish Unit Test Results'
            inputs:
                testResultsFiles: 'e2e-test-results/*.xml'
                failTaskOnFailedTests: true
            condition: succeededOrFailed()
