jobs:
    - job:
      steps:
          - template: /azure-pipelines/templates/build.yml@self

          - task: AzureCLI@2
            displayName: 'Create resources'
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm run createResources'

          - pwsh: |
                .\scripts\install-func-cli.ps1
            displayName: 'Install func cli'

          - template: /azure-pipelines/templates/build-apps.yml@self

          - template: /azure-pipelines/templates/test-node-version.yml@self
            parameters:
                nodeVersion: 18.x

          - template: /azure-pipelines/templates/test-node-version.yml@self
            parameters:
                nodeVersion: 20.x

          - template: /azure-pipelines/templates/test-node-version.yml@self
            parameters:
                nodeVersion: 22.x

          # Run tests for old config (just one Node.js version is enough)
          - template: /azure-pipelines/templates/test-node-version.yml@self
            parameters:
                nodeVersion: 18.x
                testCommand: testOldConfig

          - task: AzureCLI@2
            displayName: 'Delete resources'
            inputs:
                azureSubscription: 'nodejs-e2e-tests'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'npm run deleteResources'
            condition: succeededOrFailed()

          - task: PublishTestResults@2
            displayName: 'Publish Unit Test Results'
            inputs:
                testResultsFiles: 'e2e-test-results/*.xml'
                failTaskOnFailedTests: true
            condition: succeededOrFailed()
