jobs:
  - job: "e2etests"
    displayName: "Run Node Emulator Tests"

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux

    steps:
      - template: /azure-pipelines/templates/build.yml@self

      - pwsh: |
            npm i -g azure-functions-core-tools@4 --unsafe-perm true
        displayName: 'Install func cli'

      - template: /azure-pipelines/templates/build-apps.yml@self

      - template: /azure-pipelines/templates/test-node-version.yml@self
        parameters:
            nodeVersion: 18.x

      - template: /azure-pipelines/templates/test-node-version.yml@self
        parameters:
            nodeVersion: 20.x

      - template: /azure-pipelines/templates/test-node-version.yml@self
        parameters:
            nodeVersion: 22.x

      # These all use Cosmos - so we will come back and emulate this
      # Run tests for old config (just one Node.js version is enough)
      # - template: /azure-pipelines/templates/test-node-version.yml@self
      #   parameters:
      #       nodeVersion: 18.x
      #       testCommand: testOldConfig

      - task: PublishTestResults@2
        displayName: 'Publish Unit Test Results'
        inputs:
            testResultsFiles: 'e2e-test-results/*.xml'
            failTaskOnFailedTests: true
        condition: succeededOrFailed()