parameters:
    - name: nodeVersion
      type: string
    - name: runOldConfig
      type: boolean
      default: false

steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeVersion }}
      displayName: 'Install Node ${{ parameters.nodeVersion }}'
      retryCountOnTaskFailure: 10
    - bash: |
        docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker run --detach --publish 8081:8081 --publish 1234:1234 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        docker ps
      displayName: "Start CosmosDB Emulator"
    # - bash: |
    #     docker compose -f src/utils/sql/docker-compose.yml pull
    #     docker compose -f src/utils/sql/docker-compose.yml up -d
    #   displayName: "Start MySQL Service"
    - bash: |
        docker compose -f src/utils/servicebus/docker-compose.yml pull
        docker compose -f src/utils/servicebus/docker-compose.yml up -d
      env:
        AzureWebJobsSQLPassword: $(AzureWebJobsSQLPassword)
      displayName: 'Start ServiceBus Emulator'
    - bash: npm run testServiceBus
      displayName: 'Run ServiceBus tests Node ${{ parameters.nodeVersion }}'
      continueOnError: true
    - bash: |
        docker stop servicebus-emulator
        docker container rm --force servicebus-emulator
        docker compose -f src/utils/eventhub/docker-compose.yml pull
        docker compose -f src/utils/eventhub/docker-compose.yml up -d
      displayName: 'Stop ServiceBus Emulator and Start EventHub Emulator'
    - bash: npm run testAllExceptServiceBus
      displayName: 'Run remaining tests Node ${{ parameters.nodeVersion }}'
      continueOnError: true
    - bash: npm run testOldConfig
      displayName: 'Run oldConfig tests Node ${{ parameters.nodeVersion }}'
      condition: and(succeeded(), eq('${{ parameters.runOldConfig }}', 'true'))
      continueOnError: true