schedules:
    - cron: '0 13 * * *'
      displayName: Nightly at 6:00 AM PT
      always: true # Run even when there are no code changes
      branches:
          include:
              - main

trigger:
    batch: true
    branches:
        include:
            - main

# CI only, does not trigger on PRs.
pr: none

resources:
    pipelines:
        - pipeline: nodeLibraryV3
          project: internal
          source: nodejs-library.official
          branch: v3.x
        - pipeline: nodeLibraryV4
          project: internal
          source: nodejs-library.official
          branch: v4.x
    repositories:
        - repository: 1es
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    template: v1/1ES.Official.PipelineTemplate.yml@1es
    parameters:
        pool:
            name: 1es-pool-azfunc
            image: 1es-windows-2022
            os: windows

        sdl:
            codeql:
                runSourceLanguagesInSourceAnalysis: true

        stages:
            - stage: WindowsE2ETests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self

            - stage: LinuxE2ETests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self
              pool:
                  name: 1es-pool-azfunc
                  image: 1es-ubuntu-22.04
                  os: linux
